# Generated by Django 4.2 on 2023-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_tipo_habitacion_habitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado_seleccionado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado_ocupacion',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento')], max_length=20),
        ),
    ]
