# Generated by Django 4.2 on 2023-10-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_habitacion_estado_seleccionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado_ocupacion',
            field=models.CharField(choices=[('Ocupada', 'Ocupada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado_seleccionado',
            field=models.CharField(blank=True, choices=[('Ocupada', 'Ocupada')], max_length=20, null=True),
        ),
    ]
