# Generated by Django 4.2 on 2023-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_habitacion_estado_ocupacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='medio_pago',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='num_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
