# Generated by Django 4.2 on 2023-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_reserva_comentario_remove_reserva_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(max_length=20),
        ),
    ]
